version: '2'
services:
  dokuwiki:
    build: .
    image: mydokuwiki
    container_name: mydokuwiki
    ports:
      - '127.0.0.1:80:80'
      - '127.0.0.1:443:443'
    volumes:
      - /home/maik/data:/bitnami
    restart: always

